### PR TITLE
Use a service provider to let other languages plug into

### PR DESCRIPTION
**Pull request by ghost**
With this pull request language packages can plug into Run in Atom. This functionality would be available from version 2.0.0 on. An example is provided. I'm currently implementing a use case in the [language-ledger](https://atom.io/packages/language-ledger) package.

### CODE REVIEW

**Comment by robenkleene** [comment]
Howdy 4ourbit, thanks for the pr. But I'm not sure yet whether this functionality is appropriate for `run-in-atom`, can you tell me a bit more about your use case for [language-ledger](https://atom.io/packages/language-ledger)?

In particular, I want to make sure this use case isn't better handled by other packages designed around executing code in external processes, for example:

[script](https://atom.io/packages/script)
[atom-runner](https://atom.io/packages/atom-runner)
[script-runner](https://atom.io/packages/script-runner)

Have you looked at whether one of those packages can already be configured to accomplish the functionality you're trying to do with Ledger? In particular `script` and `atom-runner` above both look like they can be configured to support any language.

`run-in-atom` is focused on what those packages can't do, which is run JavaScript code that manipulates Atom Editor itself through it's API. Does your use case depend on that functionality?

Thanks, and cheer!
-Roben

**Comment by ghost** [comment]
Hi Roben, yes I have looked at other plugins but they are all tailored mostly to support external tools. I was looking for something higher level than that, just to retrieve code and with gfm support. From a technical view 'run-in-atom' is relatively generic in this regard, so each service consumer is to decide what running that code means.

**Comment by robenkleene** [comment]
Hi 4ourbit,

Cool, I think I get it, I had assumed that you wanted to support executing code to the ledger CLI, which seems more appropriate to these other packages. But it sounds like you're not doing this, but instead want to have the plugin itself be responsible for evaluating the code. If this is your approach, then yes I agree that would fit in nicely with `run-in-atom`.

Your implementation looks good, so I'm happy to merge this in, but it needs tests first. Here's a suggested approach to this:
1. Provide an example plugin in the [fixtures folder](https://github.com/robenkleene/run-in-atom/tree/master/spec/fixtures), this plugin's `package.json` would include the `consumedServices`, and the code would provide the service runner. The service runner could make up a grammar like `source.test`.
2. The service runner should do something easily confirmable by the test, e.g., maybe change a line of code in the active text editor. Then the test can confirm:
   1. Before running, that the line of code in the active editor does not match a test string
   2. After running, that the last line of code in the active editor does match the test string
3. I think one test is probably fine that does the following:
   1. Confirms that the line of code in the active editor does not match the test string
   2. Tries running the `source.test` grammar and confirms that an error message is shown
   3. Confirms that the line of code still does not match the test string
   4. Loads the plugin from the fixture directory. It looks like this can be done by calling  [`loadPackage`](https://github.com/atom/atom/blob/v1.0.7/src/package-manager.coffee#L345) on the `PackageManager`
   5. Runs the service and confirms that the line of code now does match the test string
   6. Unloads the package using [unloadPackage](https://github.com/atom/atom/blob/v1.0.7/src/package-manager.coffee#L379)
   7. Confirms that running the `source.test` grammar now displays the error message again.

Code from the [existing spec](https://github.com/robenkleene/run-in-atom/blob/master/spec/run-in-atom-spec.coffee) should be usable to construct the new tests, so you should only have to write new code to test the new service provider stuff and loading/unloading the package (the rest can be cut and pasted form other tests).

Please let me know if you have any questions. And yeah, I know that's quite bit of work, probably at least as much as writing the original implementation. But I hope you can see the value for the long-term maintainability of the package. The only reason I've been able to maintain this package so far (after all of Atom's API changes) is that it had full suite of tests for all of its functionality.

Also, when you have the [language-ledger](https://atom.io/packages/language-ledger) integration working, please add a link to it in the README as that would be a great resource as a reference implementation.

Thanks again, and cheers!
-Roben

**Comment by ghost** [comment]
Hey, I'm in for proper testing but it may take some time for me to grasp the relevant parts.

**Comment by robenkleene** [comment]
Great, please let me know if you have any questions.

**Pull request closed without merging**
